metric: COCO
num_classes: 91

TrainDataset:
  name: COCODataSet
  image_dir: train2017
  anno_path: zero-shot/instances_train2017_seen_2_proposal.json
  dataset_dir: dataset/coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val2017
  anno_path: zero-shot/instances_val2017_all.json
  dataset_dir: dataset/coco
  allow_empty: true
